name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/onurhanak.com
            git clone https://github.com/${{ github.repository }} ~/onurhanak.com
            cd ~/onurhanak.com
            git config --global --add safe.directory /home/ubuntu/onurhanak.com

            docker build --no-cache -t onurhanak.com .
            docker run -v ./public:/site/public --name onurhanak.com onurhanak.com
            rm -rf /tmp/public 
            cp -r ./public /tmp/public
            docker rm onurhanak.com

            sudo rm -rf /var/www/onurhanak.com/*
            sudo cp -r /tmp/public/* /var/www/onurhanak.com/
            sudo chown -R www-data:www-data /var/www/onurhanak.com
            sudo systemctl restart nginx
